Source: https://www.youtube.com/playlist?list=PLjVLYmrlmjGe-xLyoCdDrt8Nil1Alg_L3

Machine Learning Start from 25/09/2023 at 7:00 PM

Types of machine learning: Supervised, Unsupervised, and Reinforcement Learning.

1. Data Collection (Raw Data)
2. Data Preparation (Exploration)
3. Data Wrangling (Cleaning, Converting, and Usable Formating)
4. Data Modeling (Select Algorithms for Training)
5. Model Training
6. Model Test (Verification)
7. Model Deployment

Weak AI = Machine Learning >> Algorithms 
Strong AI = Deep Learning >> Multilear Neural Network

Types of Dataset: 1. Numerical Data, 2. Categorical Data, 3. Ordinal Data

Steps of Data Pre-Processing ro Exploratory Data Analysis (EDA):
1. Collecting Dataset
2. Import Python Libraries. Example: Numpy, Pandas, Matplotlib, Seaborn
3. Include Dataset in CSV Format
4. Find and Manage Null Values
5. Label Encoding for Categorical/Group Data. Example: Gender = Male, Female
6. Split Dataset for Train and Test
7. Feature Scaling

In [1]:
import numpy as np
import pandas as pd

#https://github.com/mwaskom/seaborn-data    Collect Dataset fom GitHub

In [2]:
df = pd.read_csv('Purchased.csv')
df

Country   Age  Salary Purchased
0       India   54.0  3504.0        No
1     Pakistan  65.0  3693.0       yes
2        Nepal  12.0  3436.0       yes
3       Bhutan  54.0  3433.0        No
4    Indonesia  68.0     NaN       yes
5     Malaysia  76.0  4341.0        No
6   Bangladesh  35.0  4354.0       yes
7          USA   NaN  4312.0        No
8       Canada  95.0  4425.0       yes
9    Australia  35.0  3850.0       yes
10      German  15.0  3563.0        No
11      France  35.0  3609.0        No
12   Netherlan  65.0  3761.0       yes

In [3]:
# Taking Ungrouped Column as array
indp = df[['Country', 'Age', 'Salary']].values
indp

array([['India ', 54.0, 3504.0],
       ['Pakistan', 65.0, 3693.0],
       ['Nepal', 12.0, 3436.0],
       ['Bhutan', 54.0, 3433.0],
       ['Indonesia', 68.0, nan],
       ['Malaysia', 76.0, 4341.0],
       ['Bangladesh', 35.0, 4354.0],
       ['USA', nan, 4312.0],
       ['Canada', 95.0, 4425.0],
       ['Australia', 35.0, 3850.0],
       ['German', 15.0, 3563.0],
       ['France', 35.0, 3609.0],
       ['Netherlan', 65.0, 3761.0]], dtype=object)

In [5]:
# Taking Grouped Column as array
dpn = df[['Purchased']].values
dpn

array([['No'],
       ['yes'],
       ['yes'],
       ['No'],
       ['yes'],
       ['No'],
       ['yes'],
       ['No'],
       ['yes'],
       ['yes'],
       ['No'],
       ['No'],
       ['yes']], dtype=object)

In [13]:
# Replace NAN Value with 'mean'
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_1 = imputer.fit(indp[:,1:3])
indp[:,1:3] = imputer_1.transform(indp[:,1:3])
indp


array([['India ', 54.0, 3504.0],
       ['Pakistan', 65.0, 3693.0],
       ['Nepal', 12.0, 3436.0],
       ['Bhutan', 54.0, 3433.0],
       ['Indonesia', 68.0, 3856.75],
       ['Malaysia', 76.0, 4341.0],
       ['Bangladesh', 35.0, 4354.0],
       ['USA', 50.75, 4312.0],
       ['Canada', 95.0, 4425.0],
       ['Australia', 35.0, 3850.0],
       ['German', 15.0, 3563.0],
       ['France', 35.0, 3609.0],
       ['Netherlan', 65.0, 3761.0]], dtype=object)

In [17]:
# Label Encoding for 'String' values
from sklearn.preprocessing import LabelEncoder
label_indp = LabelEncoder()
indp[:,0] = label_indp.fit_transform(indp[:,0])
indp

array([[6, 54.0, 3504.0],
       [11, 65.0, 3693.0],
       [9, 12.0, 3436.0],
       [2, 54.0, 3433.0],
       [7, 68.0, 3856.75],
       [8, 76.0, 4341.0],
       [1, 35.0, 4354.0],
       [12, 50.75, 4312.0],
       [3, 95.0, 4425.0],
       [0, 35.0, 3850.0],
       [5, 15.0, 3563.0],
       [4, 35.0, 3609.0],
       [10, 65.0, 3761.0]], dtype=object)

In [45]:
#from sklearn.preprocessing import OneHotEncoder
#ohe = OneHotEncoder()
#indpp = ohe.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()
#indpp

In [44]:
# Label Encoding for grouped 'String' values
dpn_v = LabelEncoder()
dpn = dpn_v.fit_transform(dpn)
dpn

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [46]:
# Tain and Test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(indp, dpn, test_size=0.2, random_state=0)

In [48]:
x_train

array([[5, 15.0, 3563.0],
       [9, 12.0, 3436.0],
       [3, 95.0, 4425.0],
       [11, 65.0, 3693.0],
       [12, 50.75, 4312.0],
       [0, 35.0, 3850.0],
       [2, 54.0, 3433.0],
       [6, 54.0, 3504.0],
       [8, 76.0, 4341.0],
       [10, 65.0, 3761.0]], dtype=object)

In [50]:
x_test

array([[1, 35.0, 4354.0],
       [4, 35.0, 3609.0],
       [7, 68.0, 3856.75]], dtype=object)

In [52]:
y_train

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 1], dtype=int64)

In [54]:
y_test

array([1, 0, 1], dtype=int64)

In [56]:
# Train Data Through 'StandardScaler'
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [58]:
x_train

array([[-0.41533931, -1.51385087, -0.72841046],
       [ 0.62300896, -1.63601771, -1.07256272],
       [-0.93451344,  1.74393176,  1.60748915],
       [ 1.14218309,  0.52226328, -0.37612861],
       [ 1.40177016, -0.05802925,  1.30127493],
       [-1.71327463, -0.69940521,  0.04931946],
       [-1.1941005 ,  0.07431817, -1.0806923 ],
       [-0.15575224,  0.07431817, -0.88829222],
       [ 0.36342189,  0.97020839,  1.37986088],
       [ 0.88259602,  0.52226328, -0.19185811]])

In [59]:
x_test

array([[-1.45368757, -0.69940521,  1.41508906],
       [-0.67492637, -0.69940521, -0.60375688],
       [ 0.10383483,  0.64443013,  0.06761102]])